Build IMU Program
ichiro-its/kansei pull request #4
Opened 2021-05-31 09:22 UTC by maroqijalil

2021-05-31 16:03 UTC, threeal requested changes
See individual comments for the requested changes.

2021-05-31 16:03 UTC, threeal commented on include/kansei/imu_filter.hpp
> +	ImuFilter();
Use spaces instead of tabs.

2021-05-31 16:03 UTC, threeal commented on include/kansei/imu_filter.hpp
> +	float w_bx_, w_by_, w_bz_; //
Reformat comments, and remove unused ones.

2021-05-31 16:10 UTC, threeal approved these changes
Looks good to me.

2021-06-02 19:41 UTC, finesaaa approved these changes
Good 👌

2021-06-02 19:41 UTC, merged