Change GY ACC Limit
ichiro-its/kansei pull request #9
Opened 2021-06-11 20:15 UTC by maroqijalil

2021-06-12 05:43 UTC, threeal requested changes
See individual comment for the requested changes.

2021-06-12 05:43 UTC, threeal commented on src/kansei/imu.cpp
> +  for (auto &[key, val] : imu_data.items()) {
If it's possible, try to use `const auto &`.

2021-06-12 05:43 UTC, threeal commented on src/kansei/imu.cpp
> +  nlohmann::json imu_data = nlohmann::json::parse(file);
Put a try catch here to prevent a file failed to be loaded.

2021-06-12 05:43 UTC, threeal commented on src/kansei/imu.cpp
> +      } catch (nlohmann::json::parse_error & ex) {
Use a const reference.

2021-06-12 05:43 UTC, threeal commented on include/kansei/imu.hpp
> +  float get_yaw() {return yaw;}
Use `const type & function_name() const` for a getter that return a member variable of a class. Do this to the other function too.

2021-06-12 05:43 UTC, threeal commented on src/kansei/imu.cpp
> +  fallen_left_limit = 400.0;
Put default values in the delegate (`: foo(0.0)`).

2021-06-17 06:23 UTC, threeal requested changes
Just a minor change request.

2021-06-17 06:23 UTC, threeal commented on data/kansei.json
> +  "Imu" {
Don't mix naming case in configuration file, use either classic `snake_case` or javascript's `camelCase`.

2021-06-20 06:02 UTC, threeal approved these changes
LGTM

2021-06-20 07:09 UTC, finesaaa approved these changes
Good

2021-06-20 07:09 UTC, merged